[project]
name = "finetuning-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "accelerate>=1.14.0",
    "datasets>=5.0.0",
    "evaluate>=0.4.6",
    "pandas>=3.0.3",
    "peft>=0.19.1",
    "scikit-learn>=1.9.0",
    "sentencepiece>=0.2.2",
    "tokenizers>=0.22.2",
    "torch>=2.11.0",
    "tqdm>=4.68.4",
    "transformers>=5.13.1",
]

[tool.uv.sources]
torch = { index = "pytorch-cu128" }

[[tool.uv.index]]
name = "pytorch-cu128"
url = "https://download.pytorch.org/whl/cu128"
explicit = true
